{% set version = "3.0.26" %}

package:
  name: kombu
  version: {{ version }}

source:
  fn: kombu-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/k/kombu/kombu-{{ version }}.tar.gz
  md5: dda05763cd4b72a131fe1ef9ba93d542

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - anyjson >=0.3.3
    - amqp >=1.4.6,<2.0

  run:
    - python
    - anyjson >=0.3.3
    - amqp >=1.4.6,<2.0
    - importlib # [py26]
    - ordereddict # [py26]

test:
  imports:
    - kombu
    - kombu.async
    - kombu.tests
    - kombu.tests.async
    - kombu.tests.transport
    - kombu.tests.transport.virtual
    - kombu.tests.utils
    - kombu.transport
    #- kombu.transport.django
    #- kombu.transport.django.management
    #- kombu.transport.django.management.commands
    #- kombu.transport.django.migrations
    #- kombu.transport.sqlalchemy
    - kombu.transport.librabbitmq
    - kombu.transport.pyamqp
    - kombu.transport.virtual
    - kombu.utils

  requires:
    - librabbitmq
    - amqp

about:
  home: http://kombu.readthedocs.org
  license: BSD License
  summary: Messaging library for Python

extra:
  recipe-maintainers:
    - anguslees
