{% set version = "1.6.0" %}

package:
  name: oslo.rootwrap
  version: {{ version }}

source:
  fn: oslo.rootwrap-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.rootwrap/oslo.rootwrap-{{ version }}.tar.gz
  md5: dde8877cf09581a7dd24673806f778dd

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - six >=1.9.0

test:
  imports:
    - oslo_rootwrap.cmd
    - oslo_rootwrap.client
    - oslo_rootwrap.daemon

about:
  home: https://wiki.openstack.org/wiki/Rootwrap
  license: Apache 2.0
  summary: Allow a service-specific unprivileged user to run a number of actions as the root user

extra:
  recipe-maintainers:
    - anguslees
