{% set version = "1.3.3" %}

package:
  name: retrying
  version: {{ version }}

source:
  fn: retrying-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/r/retrying/retrying-{{ version }}.tar.gz
  md5: 2a126aeef8b21324ecdeac15ff46ef17

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six >=1.7.0

  run:
    - python
    - six >=1.7.0

test:
  imports:
    - retrying

about:
  home: https://github.com/rholder/retrying
  license: Apache Software License
  summary: General-purpose retrying library

extra:
  recipe-maintainers:
    - anguslees
