{% set version = "1.9" %}

package:
  name: jsonpointer
  version: {{ version }}

source:
  fn: jsonpointer-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/j/jsonpointer/jsonpointer-{{ version }}.tar.gz
  md5: c4d3f28e72ba77062538d1c0864c40a9

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - jsonpointer

  commands:
    - jsonpointer --help

about:
  home: https://github.com/stefankoegl/python-json-pointer
  license: BSD 3-Clause
  summary: Identify specific nodes in a JSON document (RFC 6901)

extra:
  recipe-maintainers:
    - anguslees
