{% set version = "1.4.0" %}

package:
  name: traceback2
  version: {{ version }}

source:
  fn: traceback2-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/t/traceback2/traceback2-{{ version }}.tar.gz
  md5: 9e9723f4d70bfc6308fa992dd193c400

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - linecache2
    - six

test:
  imports:
    - traceback2

about:
  home: https://github.com/testing-cabal/traceback2
  license: PSF License
  summary: Backports of the traceback module

extra:
  recipe-maintainers:
    - anguslees
