{% set version = "0.7.15" %}

package:
  name: netaddr
  version: {{ version }}

source:
  fn: netaddr-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/n/netaddr/netaddr-{{ version }}.tar.gz
  md5: bd024c8f82f71fd1d90553da64735f14

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - netaddr
    - netaddr.eui
    - netaddr.ip
    - netaddr.strategy

about:
  home: https://github.com/drkjam/netaddr/
  license: BSD 3-Clause
  summary: Pythonic manipulation of IPv4, IPv6, CIDR, EUI and MAC network addresses

extra:
  recipe-maintainers:
    - anguslees
