{% set version = "1.4.6" %}

package:
  name: amqp
  version: {{ version }}

source:
  fn: amqp-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/a/amqp/amqp-{{ version }}.tar.gz
  md5: a061581b6864f838bffd62b6a3d0fb9f

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - amqp

about:
  home: http://github.com/celery/py-amqp
  license: GNU Library or Lesser General Public License (LGPL) or BSD License
  summary: Low-level AMQP client for Python (fork of amqplib)

extra:
  recipe-maintainers:
    - anguslees
