{% set version = "1.8.2" %}

package:
  name: oslo.concurrency
  version: {{ version }}

source:
  fn: oslo.concurrency-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.concurrency/oslo.concurrency-{{ version }}.tar.gz
  md5: 1ba5ae8bdbb9c12c1b6baa8e3d400b7f

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.3

  run:
    - python
    - babel >=1.3
    - iso8601 >=0.1.9
    - oslo.config <1.10.0,>=1.9.3
    - oslo.i18n <1.6.0,>=1.5.0
    - oslo.utils <1.5.0,>=1.4.0
    - posix_ipc
    - six >=1.9.0
    - "retrying !=1.3.0,>=1.2.3"

test:
  imports:
    - oslo_concurrency.lockutils
    - oslo_concurrency.processutils

about:
  home: http://docs.openstack.org/developer/oslo.concurrency/
  license: Apache Software License
  summary: Utilities for safely running multi-thread, multi-process applications using locking mechanisms and for running external processes

extra:
  recipe-maintainers:
    - anguslees
