{% set version = "2.14.0.0" %}

package:
  name: vcversioner
  version: {{ version }}

source:
  fn: vcversioner-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/v/vcversioner/vcversioner-{{ version }}.tar.gz
  md5: 7848a365ced9941053bc25d9a9f8f4b4

build:
  number: 0
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - vcversioner

about:
  home: https://github.com/habnabit/vcversioner
  license: ISC License (ISCL)
  summary: Use version control tags to discover version numbers

extra:
  recipe-maintainers:
    - anguslees
