{% set version = "1.5.2" %}

package:
  name: keystonemiddleware
  version: {{ version }}

source:
  fn: keystonemiddleware-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/k/keystonemiddleware/keystonemiddleware-{{ version }}.tar.gz
  md5: 1c6eecc1c38b290b6cffe004ce2cbdc0

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr <2.0,>=0.11

  run:
    - python
    - babel >=1.3
    - iso8601 >=0.1.9
    - oslo.config >=1.9.3,<1.10.0
    - oslo.context >=0.2.0,<0.3.0
    - oslo.i18n >=1.5.0,<1.6.0
    - oslo.serialization >=1.4.0,<1.5.0
    - oslo.utils >=1.4.0,<1.5.0
    - pycadf >=0.8.0,<0.9.0
    - python-keystoneclient >=1.1.0,<1.4.0
    - "requests >=2.2.0,!=2.4.0"
    - six >=1.9.0
    - webob >=1.2.3

test:
  imports:
    - keystonemiddleware.auth_token

about:
  home: http://docs.openstack.org/developer/keystonemiddleware/
  license: Apache Software License
  summary: Middleware for OpenStack Identity

extra:
  recipe-maintainers:
    - anguslees
