{% set version = "0.0.20" %}

package:
  name: testrepository
  version: {{ version }}

source:
  fn: testrepository-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/t/testrepository/testrepository-{{ version }}.tar.gz
  md5: f648b0aceeca4fcd5f8a62eeedea289b

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - fixtures
    - python-subunit >=0.0.18
    - testtools >=0.9.30

  run:
    - python
    - setuptools
    - fixtures
    - python-subunit >=0.0.18
    - testtools >=0.9.30

test:
  imports:
    - testrepository
    - testrepository.arguments
    - testrepository.commands
    - testrepository.repository
    - testrepository.ui

  commands:
    - testr --help

about:
  home: https://launchpad.net/testrepository
  license: BSD 3-Clause or Apache 2.0
  summary: A repository of test results.

extra:
  recipe-maintainers:
    - anguslees
