{% set version = "0.7.2" %}

package:
  name: prettytable
  version: {{ version }}

source:
  fn: prettytable-{{ version }}.tar.bz2
  url: https://pypi.python.org/packages/source/P/PrettyTable/prettytable-{{ version }}.tar.bz2
  md5: 760dc900590ac3c46736167e09fa463a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - prettytable

about:
  home: http://code.google.com/p/prettytable
  license: BSD 3-Clause
  summary: A simple Python library for easily displaying tabular data in a visually appealing ASCII table format

extra:
  recipe-maintainers:
    - anguslees
