{% set version = "0.2.0" %}

package:
  name: oslo.context
  version: {{ version }}

source:
  fn: oslo.context-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.context/oslo.context-{{ version }}.tar.gz
  md5: f6ae1896dab2c77ad016e35cd7c4a20d

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr <2.0,>=1.3

  run:
    - python

test:
  imports:
    - oslo_context.context

about:
  home: http://docs.openstack.org/developer/oslo.context/
  license: Apache 2.0
  summary: Helpers to maintain useful information about a request context

extra:
  recipe-maintainers:
    - anguslees
