{% set version = "0.5.0" %}

package:
  name: testscenarios
  version: {{ version }}

source:
  fn: testscenarios-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/t/testscenarios/testscenarios-{{ version }}.tar.gz
  md5: 859073d9e7b049aee2e6704c51f6001a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr >=0.11

  run:
    - python
    - testtools

test:
  imports:
    - testscenarios.scenarios

about:
  home: https://launchpad.net/testscenarios
  license: Apache 2.0 or BSD
  summary: A pyunit extension for dependency injection

extra:
  recipe-maintainers:
    - anguslees
