{% set version = "2015.1.1" %}

package:
  name: nova
  version: {{ version }}

source:
  fn: nova-{{ version }}.tar.gz
  url: http://tarballs.openstack.org/nova/nova-{{ version }}.tar.gz
  md5: d91d849643565145a1d6489ecc7aa7d3

build:
  number: 0
  entry_points:
    - nova-all = nova.cmd.all:main
    - nova-api = nova.cmd.api:main
    - nova-api-ec2 = nova.cmd.api_ec2:main
    - nova-api-metadata = nova.cmd.api_metadata:main
    - nova-api-os-compute = nova.cmd.api_os_compute:main
    - nova-cells = nova.cmd.cells:main
    - nova-cert = nova.cmd.cert:main
    - nova-compute = nova.cmd.compute:main
    - nova-conductor = nova.cmd.conductor:main
    - nova-console = nova.cmd.console:main
    - nova-consoleauth = nova.cmd.consoleauth:main
    - nova-dhcpbridge = nova.cmd.dhcpbridge:main
    - nova-idmapshift = nova.cmd.idmapshift:main
    - nova-manage = nova.cmd.manage:main
    - nova-network = nova.cmd.network:main
    - nova-novncproxy = nova.cmd.novncproxy:main
    - nova-objectstore = nova.cmd.objectstore:main
    - nova-rootwrap = oslo_rootwrap.cmd:main
    - nova-scheduler = nova.cmd.scheduler:main
    - nova-serialproxy = nova.cmd.serialproxy:main
    - nova-spicehtml5proxy = nova.cmd.spicehtml5proxy:main
    - nova-xvpvncproxy = nova.cmd.xvpvncproxy:main

requirements:
  build:
    - python
    - setuptools
    - pbr >=0.11,<2.0

  run:
    - python
    - sqlalchemy <=0.9.99,>=0.9.7
    - boto >=2.32.1
    - decorator >=3.4.0
    - "eventlet !=0.17.0,>=0.16.1"
    - jinja2 >=2.6
    - keystonemiddleware <1.6.0,>=1.5.0
    - lxml >=2.3
    - "routes !=2.0,!=2.1,>=1.12.3" # [py27]
    - "routes !=2.0,>=1.12.3" # [not py27]
    - webob >=1.2.3
    - greenlet >=0.3.2
    - pastedeploy >=1.5.0
    - paste
    - sqlalchemy-migrate >=0.9.5
    - netaddr >=0.7.12
    - paramiko >=1.13.0
    - pyasn1
    - babel >=1.3
    - iso8601 >=0.1.9
    - "jsonschema !=2.5.0,<3.0.0,>=2.0.0"
    - python-cinderclient <1.2.0,>=1.1.0
    - python-neutronclient <2.5.0,>=2.3.11
    - python-glanceclient <0.18.0,>=0.15.0
    - six >=1.9.0
    - stevedore <1.4.0,>=1.3.0
    - websockify <0.7,>=0.6.0
    - oslo.concurrency <1.9.0,>=1.8.0
    - oslo.config <1.10.0,>=1.9.3
    - oslo.context <0.3.0,>=0.2.0
    - oslo.log <1.1.0,>=1.0.0
    - oslo.serialization <1.5.0,>=1.4.0
    - oslo.utils <1.5.0,>=1.4.0
    - oslo.db <1.8.0,>=1.7.0
    - oslo.rootwrap <1.7.0,>=1.6.0
    - oslo.messaging <1.9.0,>=1.8.0
    - oslo.i18n <1.6.0,>=1.5.0
    - rfc3986 >=0.2.0
    - oslo.middleware <1.1.0,>=1.0.0
    - psutil <2.0.0,>=1.1.1

test:
  commands:
    - nova-all --help
    - nova-api --help
    - nova-api-ec2 --help
    - nova-api-metadata --help
    - nova-api-os-compute --help
    - nova-cells --help
    - nova-cert --help
    - nova-compute --help
    - nova-conductor --help
    - nova-console --help
    - nova-consoleauth --help
    # nova-dhcpbridge needs CONFIG_FILE pointing at a legal json file
    #- nova-dhcpbridge --help
    - nova-idmapshift --help
    - nova-manage --help
    - nova-network --help
    - nova-novncproxy --help
    - nova-objectstore --help
    # nova-rootwrap is ultra-paranoid and has no no-op command
    #- nova-rootwrap
    - nova-scheduler --help
    - nova-serialproxy --help
    - nova-spicehtml5proxy --help
    - nova-xvpvncproxy --help

about:
  home: https://wiki.openstack.org/wiki/Nova
  license: Apache Software License
  summary: OpenStack Compute (Nova)

extra:
  recipe-maintainers:
    - anguslees
