{% set version = "0.3.2" %}

package:
  name: os-brick
  version: {{ version }}

source:
  fn: os-brick-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/o/os-brick/os-brick-{{ version }}.tar.gz
  md5: 5bc611df7e5af5194b5d6fc1ce92a743

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - os_brick.initiator

about:
  home: http://docs.openstack.org/developer/os-brick/
  license: Apache Software License
  summary: OpenStack Cinder brick library for managing local volume attaches

extra:
  recipe-maintainers:
    - anguslees
