{% set version = "0.3.0" %}

package:
  name: pluggy
  version: {{ version }}

source:
  fn: pluggy-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/pluggy/pluggy-{{ version }}.tar.gz
  md5: 7e9e718884cac045efe1400c7ad016b5

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pluggy

about:
  home: https://github.com/hpk42/pluggy
  license: MIT
  summary: Plugin and hook calling mechanisms for python

extra:
  recipe-maintainers:
    - anguslees
