{% set version = "0.0.3" %}

package:
  name: extras
  version: {{ version }}

source:
  fn: extras-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/e/extras/extras-{{ version }}.tar.gz
  md5: 62d8ba049e3386a6df69b413ea81517b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - extras
    - extras.tests

about:
  home: https://github.com/testing-cabal/extras
  license: MIT
  summary: Useful extra bits for Python - things that shold be in the standard library

extra:
  recipe-maintainers:
    - anguslees
