{% set version = "1.4.0" %}

package:
  name: oslo.utils
  version: {{ version }}

source:
  fn: oslo.utils-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.utils/oslo.utils-{{ version }}.tar.gz
  md5: b488b9c25fc1ab9c563b90b937e92b61

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.3,<2.0

  run:
    - python
    - six >=1.9.0
    - babel >=1.3
    - iso8601 >=0.1.9
    - oslo.i18n >=1.3.0
    - netaddr >=0.7.12
    - netifaces >=0.10.4

test:
  imports:
    - oslo_utils.encodeutils
    - oslo_utils.eventletutils
    - oslo_utils.excutils
    - oslo_utils.importutils
    - oslo_utils.netutils
    - oslo_utils.reflection
    - oslo_utils.strutils
    - oslo_utils.timeutils
    - oslo_utils.uuidutils

about:
  home: http://docs.openstack.org/developer/oslo.utils/
  license: Apache 2.0
  summary: Common utility type functions, such as encoding, exception handling, string manipulation, and time handling

extra:
  recipe-maintainers:
    - anguslees
