{% set version = "0.1.4" %}

package:
  name: python-mimeparse
  version: {{ version }}

source:
  fn: python-mimeparse-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/python-mimeparse/python-mimeparse-{{ version }}.tar.gz
  md5: 1d2816a16f17dcfe0c613da611fe7e13

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - mimeparse

about:
  home: https://github.com/dbtsai/python-mimeparse
  license: MIT
  summary: A module provides basic functions for parsing mime-type names and matching them against a list of media-ranges.

extra:
  recipe-maintainers:
    - anguslees
