{% set version = "0.10.4" %}

package:
  name: netifaces
  version: {{ version }}

source:
  fn: netifaces-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/n/netifaces/netifaces-{{ version }}.tar.gz
  md5: 36da76e2cfadd24cc7510c2c0012eb1e

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - netifaces

about:
  home: https://bitbucket.org/al45tair/netifaces
  license: MIT
  summary: Portable network interface information.

extra:
  recipe-maintainers:
    - anguslees
