{% set version = "2.4.0" %}

package:
  name: python-neutronclient
  version: {{ version }}

source:
  fn: python-neutronclient-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/python-neutronclient/python-neutronclient-{{ version }}.tar.gz
  md5: d4305c2ca6b93f28ec8897487d76978b

build:
  number: 0
  entry_points:
    - neutron = neutronclient.shell:main

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - "pbr >=0.6,!=0.7,<1.0"
    - argparse  # [py26]
    - cliff >=1.10.0,<1.11.0
    - iso8601 >=0.1.9
    - netaddr >=0.7.12
    - oslo.i18n >=1.5.0,<1.6.0
    - oslo.serialization >=1.4.0,<1.5.0
    - oslo.utils >=1.4.0,<1.5.0
    - "requests >=2.2.0,!=2.4.0"
    - python-keystoneclient >=1.1.0
    - simplejson >=2.2.0
    - six >=1.9.0
    - babel >=1.3

test:
  imports:
    - neutronclient.client
  commands:
    - neutron --help

about:
  home: http://docs.openstack.org/developer/python-neutronclient/
  license: Apache 2.0
  summary: CLI and Client Library for OpenStack Networking

extra:
  recipe-maintainers:
    - anguslees
