{% set version = "0.7.7" %}

package:
  name: alembic
  version: {{ version }}

source:
  fn: alembic-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/a/alembic/alembic-{{ version }}.tar.gz
  md5: 8bd77f40857100da2cdcb6f5da9a7f1c

build:
  number: 0
  entry_points:
    - alembic = alembic.config:main

requirements:
  build:
    - python
    - setuptools
    - sqlalchemy >=0.7.6
    - mako

  run:
    - python
    - sqlalchemy >=0.7.6
    - mako

test:
  imports:
    - alembic
    - alembic.autogenerate
    - alembic.ddl
    - alembic.testing
    - alembic.testing.plugin

  commands:
    - alembic --help

  requires:
    - mock
    - nose >=0.11

about:
  home: http://bitbucket.org/zzzeek/alembic
  license: MIT
  summary: A database migration tool for SQLAlchemy.

extra:
  recipe-maintainers:
    - anguslees
