{% set version = "0.6.1" %}

package:
  name: websockify
  version: {{ version }}

source:
  fn: websockify-{{ version }}.zip
  url: https://pypi.python.org/packages/source/w/websockify/websockify-{{ version }}.zip
  md5: b16c07014b36f0e4fdffe61777b25a63

build:
  number: 0
  entry_points:
    - websockify = websockify.websocketproxy:websockify_init

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - websockify

  commands:
    - websockify --help

about:
  home: https://github.com/kanaka/websockify
  license: LGPLv3
  summary: WebSockets support for any application/server

extra:
  recipe-maintainers:
    - anguslees
