{% set version = "1.1.0" %}

package:
  name: warlock
  version: {{ version }}

source:
  fn: warlock-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/w/warlock/warlock-{{ version }}.tar.gz
  md5: 79649fd8096eeb0c175a193f06237676

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - jsonschema >=0.7,<3
    - jsonpatch >=0.10,<2
    - six

  run:
    - python
    - jsonschema >=0.7,<3
    - jsonpatch >=0.10,<2
    - six

test:
  imports:
    - warlock

about:
  home: http://github.com/bcwaldon/warlock
  license: Apache 2.0
  summary: Python object model built on JSON schema and JSON patch.

extra:
  recipe-maintainers:
    - anguslees
