{% set version = "2.1.1" %}

package:
  name: tox
  version: {{ version }}

source:
  fn: tox-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/t/tox/tox-{{ version }}.tar.gz
  md5: fc5b38cce701ced90a89b9da24af1769

build:
  number: 0
  entry_points:
    - tox = tox:cmdline
    - tox-quickstart = tox._quickstart:main

requirements:
  build:
    - python
    - setuptools
    - virtualenv >=1.11.2
    - py >=1.4.17
    - pluggy >=0.3.0,<0.4.0

  run:
    - python
    - virtualenv >=1.11.2
    - py >=1.4.17
    - pluggy >=0.3.0,<0.4.0

test:
  imports:
    - tox

  commands:
    - tox --version

about:
  home: http://tox.testrun.org/
  license: MIT License
  summary: virtualenv-based automation of test activities

extra:
  recipe-maintainers:
    - anguslees
