{% set version = "1.1.0" %}

package:
  name: python-subunit
  version: {{ version }}

source:
  fn: python-subunit-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/python-subunit/python-subunit-{{ version }}.tar.gz
  md5: d2c09c93346077ced675c9f718e6a0f1

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - extras
    - testtools >=0.9.34

  run:
    - python
    - extras
    - testtools >=0.9.34

test:
  # Python imports
  imports:
    - subunit

  commands:
    - subunit-1to2 --help
    - subunit-2to1 --help
    - subunit-filter --help
    - subunit-ls --help
    #- subunit-notify --help
    - subunit-output --help
    - subunit-stats --help
    #- subunit-tags --help
    - subunit2csv --help
    #- subunit2gtk --help
    #- subunit2junitxml --help
    - subunit2pyunit --help
    #- tap2subunit --help

  # requires:
    # - testscenarios

about:
  home: http://launchpad.net/subunit
  license: Apache License or BSD 3-clause License
  summary: Python implementation of subunit test streaming protocol

extra:
  recipe-maintainers:
    - anguslees
