{% set version = "0.9.7" %}

package:
  name: sqlalchemy-migrate
  version: {{ version }}

source:
  fn: sqlalchemy-migrate-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/s/sqlalchemy-migrate/sqlalchemy-migrate-{{ version }}.tar.gz
  md5: fd586f77b25f905d56d1847fc1f9c68b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - migrate = migrate.versioning.shell:main
    - migrate-repository = migrate.versioning.migrate_repository:main

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.3

  run:
    - python
    - "sqlalchemy >=0.7.8,!=0.9.5"
    - six >=1.7.0
    - decorator
    - sqlparse
    - tempita >=0.4

test:
  commands:
    - migrate --help

about:
  home: https://github.com/openstack/sqlalchemy-migrate
  license: Apache 2.0
  summary: Database schema migration for SQLAlchemy

extra:
  recipe-maintainers:
    - anguslees
