{% set version = "0.17.2" %}

package:
  name: python-glanceclient
  version: {{ version }}

source:
  fn: python-glanceclient-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/python-glanceclient/python-glanceclient-{{ version }}.tar.gz
  md5: 993840273d1e0d7fe2f1ab4bf5962c84

build:
  number: 0
  entry_points:
    - glance = glanceclient.shell:main

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - babel >=1.3
    - argparse # [py26]
    - prettytable <0.8,>=0.7
    - python-keystoneclient <1.4.0,>=1.2.0
    - pyopenssl >=0.11
    - "requests !=2.4.0,>=2.2.0"
    - warlock <2,>=1.0.1
    - six >=1.9.0
    - oslo.utils <1.5.0,>=1.4.0
    - oslo.i18n <1.6.0,>=1.5.0

test:
  imports:
    - glanceclient.client

  commands:
    - glance --help

about:
  home: http://docs.openstack.org/developer/python-glanceclient/
  license: Apache Software License
  summary: OpenStack Image API Client Library

extra:
  recipe-maintainers:
    - anguslees
