{% set version = "1.0.0" %}

package:
  name: linecache2
  version: {{ version }}

source:
  fn: linecache2-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/l/linecache2/linecache2-{{ version }}.tar.gz
  md5: 7b25d0289ec36bff1f9e63c4329ce65c
  patches:
    - inspect-fodder2-syntax-error.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python

test:
  imports:
    - linecache2

about:
  home: https://github.com/testing-cabal/linecache2
  license: Python Software Foundation License
  summary: Backports of the linecache module

extra:
  recipe-maintainers:
    - anguslees
