{% set version = "1.3.2" %}

package:
  name: python-keystoneclient
  version: {{ version }}

source:
  fn: python-keystoneclient-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/python-keystoneclient/python-keystoneclient-{{ version }}.tar.gz
  md5: b1dbec6aaa81352bb738b88dee6b251f

build:
  number: 0
  entry_points:
    - keystone = keystoneclient.shell:main

requirements:
  build:
    - python
    - setuptools
    - pbr >=0.11,<2.0

  run:
    - python
    - "pbr >=0.6,!=0.7,<1.0"
    - argparse # [py26]
    - babel >=1.3
    - iso8601 >=0.1.9
    - netaddr >=0.7.12
    - oslo.config >=1.9.3,<1.10.0
    - oslo.i18n >=1.5.0,<1.6.0
    - oslo.serialization >=1.4.0,<1.5.0
    - oslo.utils >=1.4.0,<1.5.0
    - prettytable >=0.7,<0.8
    - "requests >=2.2.0,!=2.4.0"
    - six >=1.9.0
    - stevedore >=1.3.0,<1.4.0

test:
  imports:
    - keystoneclient.client

  commands:
    - keystone --help

about:
  home: http://docs.openstack.org/developer/python-keystoneclient/
  license: Apache Software License
  summary: Client Library for OpenStack Identity

extra:
  recipe-maintainers:
    - anguslees
