{% set version = "1.9.3" %}

package:
  name: oslo.config
  version: {{ version }}

source:
  fn: oslo.config-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.config/oslo.config-{{ version }}.tar.gz
  md5: 109da1307ea8c65440accccbc59cf9a5

build:
  number: 0
  entry_points:
    - oslo-config-generator = oslo_config.generator:main

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.3

  run:
    - python
    - argparse # [py26]
    - netaddr >=0.7.12
    - six >=1.9.0
    - stevedore >=1.1.0

test:
  imports:
    - oslo_config

  commands:
    - oslo-config-generator --help

about:
  home: http://docs.openstack.org/developer/oslo.config/
  license: Apache Software License
  summary: Oslo Configuration API

extra:
  recipe-maintainers:
    - anguslees
