{% set version = "2.26.0" %}

package:
  name: python-novaclient
  version: {{ version }}

source:
  fn: python-novaclient-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/python-novaclient/python-novaclient-{{ version }}.tar.gz
  md5: 555c72f4d60292747e3ee34fbec38f28

build:
  number: 0
  entry_points:
    - nova = novaclient.shell:main

requirements:
  build:
    - python
    - setuptools
    - pbr >=0.11,<2.0

  run:
    - python
    - argparse # [py26]
    - iso8601 >=0.1.9
    - oslo.i18n >=1.5.0
    - oslo.serialization >=1.4.0
    - oslo.utils >=1.4.0
    - prettytable >=0.7,<0.8
    - requests >=2.5.2
    - simplejson >=2.2.0
    - six >=1.9.0
    - babel >=1.3
    - python-keystoneclient >=1.3.0

test:
  imports:
    - novaclient.client

  commands:
    - nova --version

about:
  home: http://docs.openstack.org/developer/python-novaclient/
  license: Apache Software License
  summary: Client library for OpenStack Compute API

extra:
  recipe-maintainers:
    - anguslees
