{% set version = "1.4.0" %}

package:
  name: oslo.serialization
  version: {{ version }}

source:
  fn: oslo.serialization-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.serialization/oslo.serialization-{{ version }}.tar.gz
  md5: e538baeb6869b4c99b94ef42916a2908

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr <2.0,>=1.3

  run:
    - python
    - babel >=1.3
    - six >=1.9.0
    - msgpack-python >=0.4.0
    - iso8601 >=0.1.9
    - oslo.utils >=1.2.0
    - pytz >=2013.6

test:
  imports:
    - oslo_serialization.jsonutils
    - oslo_serialization.msgpackutils

about:
  home: http://docs.openstack.org/developer/oslo.serialization/
  license: Apache 2.0
  summary: Support for representing objects in transmittable and storable formats, such as JSON and MessagePack.

extra:
  recipe-maintainers:
    - anguslees
