{% set version = "1.11" %}

package:
  name: jsonpatch
  version: {{ version }}

source:
  fn: jsonpatch-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/j/jsonpatch/jsonpatch-{{ version }}.tar.gz
  md5: 9f2d0aa31f99cc97089a203c5bed3924

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - jsonpointer >=1.9

  run:
    - python
    - jsonpointer >=1.9

test:
  imports:
    - jsonpatch

  commands:
    - jsondiff --help
    - jsonpatch --help

about:
  home: https://github.com/stefankoegl/python-json-patch
  license: BSD License
  summary: Apply JSON-Patches (RFC 6902)

extra:
  recipe-maintainers:
    - anguslees
