{% set version = "0.17.4" %}

package:
  name: eventlet
  version: {{ version }}

source:
  fn: eventlet-{{ version }}.tar.gz
  url: http://pypi.python.org/packages/source/e/eventlet/eventlet-{{ version }}.tar.gz
  md5: fea0993b14cc7322f944bdd535c4f24a

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - greenlet >=0.3

  run:
    - python
    - greenlet >=0.3

test:
  imports:
    - eventlet
    - eventlet.green
    - eventlet.green.OpenSSL
    - eventlet.green.http  # [py3k]
    - eventlet.green.urllib
    - eventlet.greenio
    - eventlet.hubs
    - eventlet.support

  requires:
    - pyopenssl

about:
  home: http://eventlet.net
  license: MIT License
  summary: Highly concurrent networking library

extra:
  recipe-maintainers:
    - anguslees
