{% set version = "0.2.7" %}

package:
  name: testresources
  version: {{ version }}

source:
  fn: testresources-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/t/testresources/testresources-{{ version }}.tar.gz
  md5: db2e774be2a6f5754cbbf4c537f823d0

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - testresources
    - testresources.tests

about:
  home: https://launchpad.net/testresources
  license: BSD License or Apache Software License
  summary: A pyunit extension for managing expensive test resources

extra:
  recipe-maintainers:
    - anguslees
