{% set version = "0.3" %}

package:
  name: monotonic
  version: {{ version }}

source:
  fn: monotonic-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/m/monotonic/monotonic-{{ version }}.tar.gz
  md5: 4d055924b13474f5ac65385b937124fe

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - monotonic

about:
  home: https://github.com/atdt/monotonic
  license: Apache 2.0
  summary: An implementation of time.monotonic() for Python 2 & < 3.3

extra:
  recipe-maintainers:
    - anguslees
