{% set version = "1.1.2" %}

package:
  name: python-cinderclient
  version: {{ version }}

source:
  fn: python-cinderclient-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/python-cinderclient/python-cinderclient-{{ version }}.tar.gz
  md5: c22e0e397ea1dc4d21862c07b9b949b1

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - cinder = cinderclient.shell:main

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - argparse  # [py26]
    - prettytable <0.8,>=0.7
    - python-keystoneclient <1.4.0,>=1.2.0
    - "requests !=2.4.0,>=2.2.0"
    - simplejson >=2.2.0
    - babel >=1.3
    - six >=1.9.0

test:
  imports:
    - cinderclient.client

  commands:
    - cinder --help

about:
  home: http://docs.openstack.org/developer/python-cinderclient/
  license: Apache 2.0
  summary: OpenStack Block Storage API Client Library

extra:
  recipe-maintainers:
    - anguslees
