{% set version = "0.6.8" %}

package:
  name: cmd2
  version: {{ version }}

source:
  fn: cmd2-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/c/cmd2/cmd2-{{ version }}.tar.gz
  md5: c32c9a897e010c977b50c1ddc13f09fe

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyparsing >=2.0.1

  run:
    - python
    - pyparsing >=2.0.1

test:
  imports:
    - cmd2

about:
  home: http://packages.python.org/cmd2/
  license: MIT License
  summary: "Extra features for standard library's cmd module"

extra:
  recipe-maintainers:
    - anguslees
