{% set version = "1.6.1" %}

package:
  name: librabbitmq
  version: {{ version }}

source:
  fn: librabbitmq-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/l/librabbitmq/librabbitmq-{{ version }}.tar.gz
  md5: 716f05388d4747ea605c1a31f8541e3b

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - amqp >=1.4.6

  run:
    - python
    - amqp >=1.4.6

test:
  imports:
    - funtests
    - funtests.tests
    - librabbitmq
    - librabbitmq.tests

about:
  home: http://github.com/celery/librabbitmq
  license: MPL 1.0
  summary: AMQP Client using the rabbitmq-c library.

extra:
  recipe-maintainers:
    - anguslees
