{% set version = "1.3.0" %}

package:
  name: stevedore
  version: {{ version }}

source:
  fn: stevedore-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/s/stevedore/stevedore-{{ version }}.tar.gz
  md5: e9ed2a1cf91ee76fd9045f902fa58089

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr >=1.3

  run:
    - python
    - argparse  # [py26]
    - six >=1.9.0

test:
  imports:
    - stevedore

about:
  home: http://docs.openstack.org/developer/stevedore/
  license: Apache 2.0
  summary: Manage dynamic plugins for Python applications

extra:
  recipe-maintainers:
    - anguslees
