{% set version = "1.0.0" %}

package:
  name: oslo.middleware
  version: {{ version }}

source:
  fn: oslo.middleware-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.middleware/oslo.middleware-{{ version }}.tar.gz
  md5: 5102848f299c777e8333d207149e87ab

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - babel >=1.3
    - oslo.config >=1.9.0
    - oslo.context >=0.2.0
    - oslo.i18n >=1.3.0
    - six >=1.9.0
    - stevedore >=1.1.0
    - webob >=1.2.3

test:
  imports:
    - oslo.middleware

about:
  home: http://docs.openstack.org/developer/oslo.middleware/
  license: Apache Software License
  summary: Oslo Middleware library

extra:
  recipe-maintainers:
    - anguslees
