{% set version = "1.8.3" %}

package:
  name: oslo.messaging
  version: {{ version }}

source:
  fn: oslo.messaging-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/o/oslo.messaging/oslo.messaging-{{ version }}.tar.gz
  md5: cba1896eca1f2c9bcf8dac0979842c00

build:
  number: 0
  entry_points:
    - oslo-messaging-zmq-receiver = oslo_messaging._cmd.zmq_receiver:main

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - oslo.config >=1.9.3,<1.10.0
    - oslo.utils >=1.4.0,<1.5.0
    - oslo.serialization >=1.4.0,<1.5.0
    - oslo.i18n >=1.5.0,<1.6.0
    - stevedore >=1.3.0,<1.4.0
    - six >=1.9.0
    - "eventlet >=0.16.1,!=0.17.0"
    - pyyaml >=3.1.0
    - oslo.middleware >=1.0.0,<1.1.0
    # Used by rabbit/amqp executor
    - kombu >=2.5.0
    # Used by futures based executor
    - futures >=2.1.6
    # Used by aioeventlet executor (todo: package these)
    #- aioeventlet >=0.4
    #- trollius >=1.0

test:
  imports:
    - oslo_messaging.server
    - oslo_messaging._drivers.impl_rabbit
    - oslo_messaging._drivers.impl_qpid
    - oslo_messaging._drivers.impl_zmq
    #- oslo_messaging._drivers.protocols.amqp.driver
    - oslo_messaging._drivers.impl_rabbit
    - oslo_messaging._drivers.impl_fake
    #- oslo_messaging._executors.impl_aioeventlet
    - oslo_messaging._executors.impl_blocking
    - oslo_messaging._executors.impl_eventlet
    - oslo_messaging._executors.impl_thread

  commands:
    - oslo-messaging-zmq-receiver --help

about:
  home: http://docs.openstack.org/developer/oslo.messaging/
  license: Apache 2.0
  summary: RPC and notifications over a number of different messaging transports

extra:
  recipe-maintainers:
    - anguslees
