{% set version = "1.10.1" %}

package:
  name: cliff
  version: {{ version }}

source:
  fn: cliff-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/c/cliff/cliff-{{ version }}.tar.gz
  md5: 224f9a21c697795ab4f558f868f97633

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - argparse  # [py26]
    - cmd2 >=0.6.7
    - prettytable >=0.7,<0.8
    - pyparsing >=2.0.1
    - six >=1.9.0
    - stevedore >=1.1.0

test:
  imports:
    - cliff.app

about:
  home: http://docs.openstack.org/developer/cliff/
  license: Apache 2.0
  summary: Command Line Interface Formulation Framework

extra:
  recipe-maintainers:
    - anguslees
