{% set version = "0.2.2" %}

package:
  name: rfc3986
  version: {{ version }}

source:
  fn: rfc3986-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/r/rfc3986/rfc3986-{{ version }}.tar.gz
  md5: 818c7851fd49ecb83c89856a9962959e

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - rfc3986

about:
  home: https://rfc3986.rtfd.org
  license: Apache Software License
  summary: Validating URI References per RFC 3986

extra:
  recipe-maintainers:
    - anguslees
