{% set version = "0.7.0" %}

package:
  name: debtcollector
  version: {{ version }}

source:
  fn: debtcollector-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/d/debtcollector/debtcollector-{{ version }}.tar.gz
  md5: 5f764e8d91a1b5e9580abc4854151f2e

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr <2.0,>=1.3

  run:
    - python
    - pbr <2.0,>=1.3
    - babel >=1.3
    - six >=1.9.0
    - wrapt >=1.7.0

test:
  imports:
    - debtcollector

about:
  home: http://docs.openstack.org/developer/debtcollector/
  license: Apache 2.0
  summary: A collection of Python deprecation patterns and strategies that help you collect your technical debt in a non-destructive manner.

extra:
  recipe-maintainers:
    - anguslees
