{% set version = "1.8.0" %}

package:
  name: testtools
  version: {{ version }}

source:
  fn: testtools-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/t/testtools/testtools-{{ version }}.tar.gz
  md5: 89965b0b39930c0d1f5e07c6f545e6a0

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr >=0.11

  run:
    - python
    - pbr >=0.11
    - python-mimeparse
    - unittest2 >=1.0.0
    - traceback2
    - extras

test:
  imports:
    - testtools

about:
  home: https://github.com/testing-cabal/testtools
  license: MIT License
  summary: Extensions to the Python standard library unit testing framework

extra:
  recipe-maintainers:
    - anguslees
