{% set version = "0.8.0" %}

package:
  name: pycadf
  version: {{ version }}

source:
  fn: pycadf-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/pycadf/pycadf-{{ version }}.tar.gz
  md5: 3a9f439003ed165db7e9a7ef1d360259

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pbr

  run:
    - python
    - oslo.config >=1.6.0
    - oslo.context >=0.1.0
    - oslo.i18n >=1.3.0
    - oslo.serialization >=1.2.0
    - pytz >=2013.6
    - six >=1.7.0
    - webob >=1.2.3

test:
  imports:
    - pycadf.cadftaxonomy
    - pycadf.cadftype
    - pycadf.credential
    - pycadf.endpoint
    - pycadf.eventfactory
    - pycadf.host
    - pycadf.identifier
    - pycadf.reason
    - pycadf.reporterstep
    - pycadf.resource
    - pycadf.tag
    - pycadf.timestamp

about:
  home: http://docs.openstack.org/developer/pycadf/
  license: Apache 2.0
  summary: Python implementation of the CADF specification

extra:
  recipe-maintainers:
    - anguslees
